name: wcwrapped_flutter
description: Flutter version of the wrapped-style OneFootball recap prototype.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/entry-screen/
    - assets/images/page-1/
    - assets/images/page-2/
    - assets/images/page-4/
    - assets/images/page-5/
    - assets/images/page-6/
    - assets/images/page-7/
    - assets/images/page-8/
    - assets/images/shared/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: Druk
      fonts:
        - asset: assets/fonts/DrukLCG-Bold.ttf